// Generated by ProxyPESourceGenerator

#include "ProxyLibraryGlobals.h"

LPCSTR libraryFilePath = "%SystemRoot%\\System32\\msimg32.dll";
SIZE_T symbolCount = 5;
FARPROC symbolAddressArray[5];
LPCSTR symbolNameArray[5] = {
    "AlphaBlend",
    "DllInitialize",
    "GradientFill",
    "TransparentBlt",
    "vSetDdrawflag",
};
