; Generated by ProxyPESourceGenerator

.model flat, stdcall

.data
extern symbolAddressArray:dword

.code
AlphaBlend proc
    jmp symbolAddressArray+0
AlphaBlend endp
DllInitialize proc
    jmp symbolAddressArray+4
DllInitialize endp
GradientFill proc
    jmp symbolAddressArray+8
GradientFill endp
TransparentBlt proc
    jmp symbolAddressArray+12
TransparentBlt endp
vSetDdrawflag proc
    jmp symbolAddressArray+16
vSetDdrawflag endp
end
